WITH RECURSIVE HOURS AS ( -- 쿼리 내에서만 사용할 테이블 생성
    SELECT 0 AS HOUR      -- RECURSIVE의 시작점(한 번만 실행)
    UNION ALL             -- RECURSIVE 결과와 시작점 합치기
    SELECT HOUR + 1       -- RECURSIVE 멤버
    FROM HOURS
    WHERE HOUR < 23
)
SELECT H.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HOURS H
LEFT JOIN ANIMAL_OUTS A
    ON H.HOUR = HOUR(A.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR;