SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS D
WHERE EXISTS (SELECT CODE
                   FROM SKILLCODES AS S
                   WHERE (NAME = 'Python' OR NAME = 'C#') AND D.SKILL_CODE & S.CODE > 0)
ORDER BY ID;