SELECT YEAR(X.DIFFERENTIATION_DATE) AS YEAR, Y.MAX_SIZE - X.SIZE_OF_COLONY AS YEAR_DEV, X.ID
FROM ECOLI_DATA AS X
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS Y
ON YEAR(X.DIFFERENTIATION_DATE) = Y.YEAR
ORDER BY YEAR(X.DIFFERENTIATION_DATE), YEAR_DEV;